### ISSUE TITLE
Ctrl+I combination for formatting not working in qtcreator

### ISSUE THREAD

**Issue by Miv2nir** [NChechulin/DSBA-autoformatting-setup#1]
The title is self-explanatory. After following the guide, read on google that ctrl+I key combo should format the code, but it does nothing

**Comment by NChechulin** [comment]
Should be fixed in [e2384ab](https://github.com/NChechulin/DSBA-autoformatting-setup/commit/7ad79c8ff1086764ae638069952213500b5889d0) but I won't close the issue for now
